import type { NodeTypeDef } from "./types";

/**
 * Helper: produce a JS string literal that can embed ${...} templates resolved
 * at runtime by the exported bot's `resolve()` helper.
 */
const j = (s: unknown) => JSON.stringify(s ?? "");

export const NODE_TYPES: NodeTypeDef[] = [
  // ───────────── TRIGGERS ─────────────
  {
    type: "trigger.messageCreate",
    category: "trigger",
    label: "On Message",
    description: "Fires when any message is sent",
    inputs: 0,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "match", label: "Content matches (optional)", type: "text", placeholder: "!ping" },
      { key: "matchMode", label: "Match mode", type: "select", default: "equals", options: [
        { label: "Equals", value: "equals" },
        { label: "Contains", value: "contains" },
        { label: "Starts with", value: "startsWith" },
        { label: "Regex", value: "regex" },
      ]},
    ],
    codegen: (d) => `// trigger handled by event router (messageCreate)`,
  },
  { type: "trigger.messageUpdate", category: "trigger", label: "On Message Edit", description: "Fires on message edit", inputs: 0, outputs: [{ id: "out", label: "Then" }], fields: [] },
  { type: "trigger.messageDelete", category: "trigger", label: "On Message Delete", description: "Fires on message delete", inputs: 0, outputs: [{ id: "out", label: "Then" }], fields: [] },
  { type: "trigger.guildMemberAdd", category: "trigger", label: "On Member Join", description: "Fires when a member joins", inputs: 0, outputs: [{ id: "out", label: "Then" }], fields: [] },
  {
    type: "trigger.slashCommand",
    category: "trigger",
    label: "Slash Command",
    description: "Registers and handles a slash command",
    inputs: 0,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "name", label: "Command name", type: "text", required: true, placeholder: "ping" },
      { key: "description", label: "Description", type: "text", default: "No description" },
    ],
  },
  {
    type: "trigger.buttonInteraction",
    category: "trigger",
    label: "Button Click",
    description: "Fires when a button with the given customId is clicked",
    inputs: 0,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "customId", label: "Custom ID", type: "text", required: true }],
  },
  {
    type: "trigger.selectMenuInteraction",
    category: "trigger",
    label: "Select Menu",
    description: "Fires when a select menu submits",
    inputs: 0,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "customId", label: "Custom ID", type: "text", required: true }],
  },
  {
    type: "trigger.scheduled",
    category: "trigger",
    label: "Schedule (Cron)",
    description: "Runs on a cron schedule",
    inputs: 0,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "cron", label: "Cron expression", type: "text", default: "*/5 * * * *" }],
  },
  {
    type: "trigger.webhook",
    category: "trigger",
    label: "Webhook",
    description: "HTTP webhook endpoint",
    inputs: 0,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "path", label: "Path", type: "text", default: "/hook" }],
  },
  {
    type: "trigger.manual",
    category: "trigger",
    label: "Manual / Test",
    description: "Manual trigger for testing in the sandbox",
    inputs: 0,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "payload", label: "Mock payload (JSON)", type: "json", default: '{"username":"tester","userId":"1","message":"hi"}' }],
  },

  // ───────────── CONDITIONS ─────────────
  {
    type: "condition.if",
    category: "condition",
    label: "If / Else",
    description: "Branch on a comparison",
    inputs: 1,
    outputs: [{ id: "true", label: "True" }, { id: "false", label: "False" }],
    fields: [
      { key: "left", label: "Left", type: "text", placeholder: "${message}" },
      { key: "op", label: "Operator", type: "select", default: "equals", options: [
        { label: "equals", value: "equals" },
        { label: "contains", value: "contains" },
        { label: "startsWith", value: "startsWith" },
        { label: "endsWith", value: "endsWith" },
        { label: "regex", value: "regex" },
        { label: "!=", value: "neq" },
        { label: ">", value: "gt" },
        { label: "<", value: "lt" },
      ]},
      { key: "right", label: "Right", type: "text" },
    ],
    codegen: (d) => `branch = ctx.compare(${j(d.left)}, ${j(d.op)}, ${j(d.right)});`,
  },
  {
    type: "condition.switch",
    category: "condition",
    label: "Switch",
    description: "Multi-way branch",
    inputs: 1,
    outputs: [
      { id: "case1", label: "Case 1" },
      { id: "case2", label: "Case 2" },
      { id: "case3", label: "Case 3" },
      { id: "default", label: "Default" },
    ],
    fields: [
      { key: "value", label: "Value", type: "text", placeholder: "${message}" },
      { key: "case1", label: "Case 1 value", type: "text" },
      { key: "case2", label: "Case 2 value", type: "text" },
      { key: "case3", label: "Case 3 value", type: "text" },
    ],
  },
  {
    type: "condition.userRoleCheck",
    category: "condition",
    label: "User has Role",
    description: "Branch if the user has a role",
    inputs: 1,
    outputs: [{ id: "true", label: "Yes" }, { id: "false", label: "No" }],
    fields: [{ key: "roleId", label: "Role ID", type: "text", required: true }],
  },

  // ───────────── LOGIC ─────────────
  {
    type: "logic.loop",
    category: "logic",
    label: "Loop (times)",
    description: "Repeat the body N times",
    inputs: 1,
    outputs: [{ id: "body", label: "Body" }, { id: "done", label: "Done" }],
    fields: [{ key: "times", label: "Times", type: "number", default: 3 }],
  },
  {
    type: "logic.parallel",
    category: "logic",
    label: "Parallel",
    description: "Run all outputs in parallel",
    inputs: 1,
    outputs: [{ id: "a", label: "A" }, { id: "b", label: "B" }, { id: "c", label: "C" }],
    fields: [],
  },
  {
    type: "logic.tryCatch",
    category: "logic",
    label: "Try / Catch",
    description: "Catch errors from a sub-branch",
    inputs: 1,
    outputs: [{ id: "try", label: "Try" }, { id: "catch", label: "Catch" }],
    fields: [],
  },
  {
    type: "logic.subflow",
    category: "logic",
    label: "Call Subflow",
    description: "Execute another flow as a subroutine",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "flowId", label: "Flow ID", type: "text", required: true }],
  },

  // ───────────── ACTIONS — MESSAGING ─────────────
  {
    type: "action.sendMessage",
    category: "action",
    label: "Send Message",
    description: "Send a message to a channel",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "channelId", label: "Channel ID (blank = current)", type: "text" },
      { key: "content", label: "Content", type: "textarea", required: true, placeholder: "Hello ${username}!" },
    ],
    codegen: (d) => `await ctx.sendMessage(${j(d.channelId)}, ${j(d.content)});`,
  },
  {
    type: "action.sendEmbed",
    category: "action",
    label: "Send Embed",
    description: "Send a rich embed",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "channelId", label: "Channel ID", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "color", label: "Color (hex)", type: "text", default: "#5865F2" },
    ],
    codegen: (d) => `await ctx.sendEmbed(${j(d.channelId)}, { title: ${j(d.title)}, description: ${j(d.description)}, color: ${j(d.color)} });`,
  },
  {
    type: "action.reply",
    category: "action",
    label: "Reply",
    description: "Reply to the trigger message",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "content", label: "Content", type: "textarea", required: true }],
    codegen: (d) => `await ctx.reply(${j(d.content)});`,
  },
  {
    type: "action.editMessage",
    category: "action",
    label: "Edit Message",
    description: "Edit a previously sent message",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "messageId", label: "Message ID", type: "text" },
      { key: "channelId", label: "Channel ID", type: "text" },
      { key: "content", label: "New content", type: "textarea" },
    ],
  },
  {
    type: "action.deleteMessage",
    category: "action",
    label: "Delete Message",
    description: "Delete a message",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "messageId", label: "Message ID", type: "text" },
      { key: "channelId", label: "Channel ID", type: "text" },
    ],
  },
  {
    type: "action.dm",
    category: "action",
    label: "Send DM",
    description: "Send a direct message to a user",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "userId", label: "User ID", type: "text", required: true },
      { key: "content", label: "Content", type: "textarea", required: true },
    ],
    codegen: (d) => `await ctx.dm(${j(d.userId)}, ${j(d.content)});`,
  },

  // ───────────── ACTIONS — MODERATION ─────────────
  { type: "action.ban", category: "action", label: "Ban User", description: "Ban a user", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "userId", label: "User ID", type: "text", required: true }, { key: "reason", label: "Reason", type: "text" }], codegen: (d) => `await ctx.ban(${j(d.userId)}, ${j(d.reason)});` },
  { type: "action.kick", category: "action", label: "Kick User", description: "Kick a user", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "userId", label: "User ID", type: "text", required: true }, { key: "reason", label: "Reason", type: "text" }], codegen: (d) => `await ctx.kick(${j(d.userId)}, ${j(d.reason)});` },
  { type: "action.timeout", category: "action", label: "Timeout User", description: "Timeout a user (ms)", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "userId", label: "User ID", type: "text", required: true }, { key: "duration", label: "Duration (ms)", type: "number", default: 60000 }], codegen: (d) => `await ctx.timeout(${j(d.userId)}, ${Number(d.duration)||60000});` },
  { type: "action.untimeout", category: "action", label: "Remove Timeout", description: "Remove a user's timeout", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "userId", label: "User ID", type: "text", required: true }] },
  { type: "action.addRole", category: "action", label: "Add Role", description: "Give a role to a user", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "userId", label: "User ID", type: "text", required: true }, { key: "roleId", label: "Role ID", type: "text", required: true }], codegen: (d) => `await ctx.addRole(${j(d.userId)}, ${j(d.roleId)});` },
  { type: "action.removeRole", category: "action", label: "Remove Role", description: "Remove a role from a user", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "userId", label: "User ID", type: "text", required: true }, { key: "roleId", label: "Role ID", type: "text", required: true }] },

  // ───────────── ACTIONS — SERVER ─────────────
  { type: "action.createChannel", category: "action", label: "Create Channel", description: "Create a text channel", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "name", label: "Name", type: "text", required: true }] },
  { type: "action.deleteChannel", category: "action", label: "Delete Channel", description: "Delete a channel", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "channelId", label: "Channel ID", type: "text", required: true }] },
  { type: "action.renameChannel", category: "action", label: "Rename Channel", description: "Rename a channel", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "channelId", label: "Channel ID", type: "text", required: true }, { key: "name", label: "New name", type: "text", required: true }] },
  { type: "action.createRole", category: "action", label: "Create Role", description: "Create a role", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "name", label: "Name", type: "text", required: true }] },
  { type: "action.deleteRole", category: "action", label: "Delete Role", description: "Delete a role", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "roleId", label: "Role ID", type: "text", required: true }] },

  // ───────────── INTERACTIONS ─────────────
  {
    type: "interaction.reply",
    category: "interaction",
    label: "Interaction Reply",
    description: "Reply to an interaction",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "content", label: "Content", type: "textarea", required: true },
      { key: "ephemeral", label: "Ephemeral (only user sees)", type: "boolean", default: false },
    ],
    codegen: (d) => `await ctx.iReply(${j(d.content)}, ${d.ephemeral ? "true" : "false"});`,
  },
  { type: "interaction.deferReply", category: "interaction", label: "Defer Reply", description: "Defer the interaction reply", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "ephemeral", label: "Ephemeral", type: "boolean", default: false }] },
  { type: "interaction.editReply", category: "interaction", label: "Edit Reply", description: "Edit the deferred reply", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "content", label: "Content", type: "textarea", required: true }] },
  { type: "interaction.followUp", category: "interaction", label: "Follow Up", description: "Send a follow-up message", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "content", label: "Content", type: "textarea", required: true }, { key: "ephemeral", label: "Ephemeral", type: "boolean", default: false }] },
  { type: "interaction.update", category: "interaction", label: "Update Message", description: "Update the original interaction message", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "content", label: "Content", type: "textarea" }] },
  { type: "interaction.disableComponents", category: "interaction", label: "Disable Components", description: "Disable buttons/menus on the message", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [] },
  {
    type: "interaction.button",
    category: "interaction",
    label: "Add Button",
    description: "Attach a button to the next reply",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "label", label: "Label", type: "text", required: true },
      { key: "customId", label: "Custom ID", type: "text", required: true },
      { key: "style", label: "Style", type: "select", default: "Primary", options: [
        { label: "Primary", value: "Primary" },
        { label: "Secondary", value: "Secondary" },
        { label: "Success", value: "Success" },
        { label: "Danger", value: "Danger" },
        { label: "Link", value: "Link" },
      ]},
      { key: "url", label: "URL (Link style only)", type: "text" },
      { key: "emoji", label: "Emoji", type: "text" },
      { key: "disabled", label: "Disabled", type: "boolean", default: false },
    ],
  },
  {
    type: "interaction.selectMenu",
    category: "interaction",
    label: "Add Select Menu",
    description: "Attach a select menu to the next reply",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "customId", label: "Custom ID", type: "text", required: true },
      { key: "kind", label: "Kind", type: "select", default: "string", options: [
        { label: "String", value: "string" },
        { label: "User", value: "user" },
        { label: "Role", value: "role" },
        { label: "Channel", value: "channel" },
      ]},
      { key: "options", label: "Options (JSON for string menu)", type: "json", default: '[{"label":"A","value":"a"}]' },
      { key: "min", label: "Min values", type: "number", default: 1 },
      { key: "max", label: "Max values", type: "number", default: 1 },
    ],
  },

  // ───────────── API ─────────────
  {
    type: "api.request",
    category: "api",
    label: "API Request",
    description: "Call an HTTP API",
    inputs: 1,
    outputs: [{ id: "ok", label: "Success" }, { id: "err", label: "Failure" }],
    fields: [
      { key: "method", label: "Method", type: "select", default: "GET", options: ["GET","POST","PUT","PATCH","DELETE"].map(v=>({label:v,value:v})) },
      { key: "url", label: "URL", type: "text", required: true, placeholder: "https://api.example.com/x" },
      { key: "headers", label: "Headers (JSON)", type: "json", default: "{}" },
      { key: "body", label: "Body (JSON)", type: "json", default: "" },
      { key: "extract", label: "Extract (var=path lines)", type: "textarea", placeholder: "ltc_price=litecoin.usd" },
    ],
    codegen: (d) => `await ctx.api(${j(d.method)}, ${j(d.url)}, ${j(d.headers)}, ${j(d.body)}, ${j(d.extract)});`,
  },

  // ───────────── DELAY ─────────────
  {
    type: "delay.wait",
    category: "delay",
    label: "Delay",
    description: "Wait for a duration",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "ms", label: "Milliseconds", type: "number", default: 1000 }],
    codegen: (d) => `await ctx.sleep(${Number(d.ms)||0});`,
  },
  {
    type: "delay.cooldown",
    category: "delay",
    label: "Cooldown",
    description: "Per-user cooldown (skip if hit)",
    inputs: 1,
    outputs: [{ id: "ok", label: "Allowed" }, { id: "blocked", label: "Blocked" }],
    fields: [
      { key: "key", label: "Cooldown key", type: "text", default: "default" },
      { key: "ms", label: "Cooldown (ms)", type: "number", default: 5000 },
    ],
  },

  // ───────────── STORAGE ─────────────
  { type: "storage.set", category: "storage", label: "Storage Set", description: "Save a value", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "key", label: "Key", type: "text", required: true }, { key: "value", label: "Value", type: "text", required: true }], codegen: (d) => `await ctx.storeSet(${j(d.key)}, ${j(d.value)});` },
  { type: "storage.get", category: "storage", label: "Storage Get", description: "Read a value into a variable", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "key", label: "Key", type: "text", required: true }, { key: "varName", label: "Save as variable", type: "text", required: true }], codegen: (d) => `await ctx.storeGet(${j(d.key)}, ${j(d.varName)});` },
  { type: "storage.delete", category: "storage", label: "Storage Delete", description: "Delete a value", inputs: 1, outputs: [{ id: "out", label: "Then" }], fields: [{ key: "key", label: "Key", type: "text", required: true }] },

  // ───────────── UTILITY ─────────────
  {
    type: "utility.randomKey",
    category: "utility",
    label: "Random Key",
    description: "Generate a random string and save as variable",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "length", label: "Length", type: "number", default: 16 },
      { key: "upper", label: "Uppercase", type: "boolean", default: true },
      { key: "lower", label: "Lowercase", type: "boolean", default: true },
      { key: "numbers", label: "Numbers", type: "boolean", default: true },
      { key: "symbols", label: "Symbols", type: "boolean", default: false },
      { key: "varName", label: "Save as variable", type: "text", default: "key" },
    ],
    codegen: (d) => `ctx.randomKey({length:${Number(d.length)||16}, upper:${!!d.upper}, lower:${!!d.lower}, numbers:${!!d.numbers}, symbols:${!!d.symbols}, varName:${j(d.varName)}});`,
  },
  {
    type: "utility.transcript",
    category: "utility",
    label: "Transcript",
    description: "Generate a channel transcript and send it",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "channelId", label: "Source channel ID", type: "text", required: true },
      { key: "format", label: "Format", type: "select", default: "html", options: [{label:"HTML",value:"html"},{label:"Text",value:"text"}] },
      { key: "destType", label: "Send to", type: "select", default: "channel", options: [{label:"Channel",value:"channel"},{label:"DM user",value:"user"}] },
      { key: "destId", label: "Destination ID", type: "text", required: true },
      { key: "limit", label: "Message limit", type: "number", default: 100 },
    ],
    codegen: (d) => `await ctx.transcript(${j(d.channelId)}, ${j(d.format)}, ${j(d.destType)}, ${j(d.destId)}, ${Number(d.limit)||100});`,
  },
  {
    type: "utility.log",
    category: "utility",
    label: "Log",
    description: "Print to the bot console / sandbox log",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [{ key: "message", label: "Message", type: "textarea", default: "" }],
    codegen: (d) => `ctx.log("info", ${j(d.message)});`,
  },
  {
    type: "utility.accessControl",
    category: "utility",
    label: "Access Control",
    description: "Allow only listed users/roles past this gate",
    inputs: 1,
    outputs: [{ id: "ok", label: "Allowed" }, { id: "denied", label: "Denied" }],
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", default: true },
      { key: "userIds", label: "Allowed user IDs (comma)", type: "text" },
      { key: "roleIds", label: "Allowed role IDs (comma)", type: "text" },
    ],
  },
  {
    type: "utility.setVariable",
    category: "utility",
    label: "Set Variable",
    description: "Set a workflow variable",
    inputs: 1,
    outputs: [{ id: "out", label: "Then" }],
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "value", label: "Value", type: "text", required: true },
    ],
    codegen: (d) => `ctx.setVar(${j(d.name)}, ${j(d.value)});`,
  },
];

export const NODE_MAP: Record<string, NodeTypeDef> = Object.fromEntries(
  NODE_TYPES.map((n) => [n.type, n]),
);

export const CATEGORY_LABELS: Record<string, string> = {
  trigger: "Triggers",
  condition: "Conditions",
  logic: "Logic",
  action: "Actions",
  interaction: "Interactions",
  api: "API",
  delay: "Delay",
  storage: "Storage",
  utility: "Utilities",
  subflow: "Subflows",
};

export const CATEGORY_COLORS: Record<string, string> = {
  trigger: "var(--cat-trigger)",
  condition: "var(--cat-condition)",
  logic: "var(--cat-logic)",
  action: "var(--cat-action)",
  interaction: "var(--cat-interaction)",
  api: "var(--cat-api)",
  delay: "var(--cat-delay)",
  storage: "var(--cat-storage)",
  utility: "var(--cat-utility)",
  subflow: "var(--cat-subflow)",
};